repos:
  - repo: local
    hooks:
      - id: make-format
        name: Make Format
        entry: make format  # This is the command that the hook will run
        language: system
        types: [python]