repos:
- repo: local
  hooks:
  - id: make-format
    name: Make Format
    entry: make format  # This is the command that the hook will run
    language: system
    types: [ python ]

- repo: https://github.com/kieran-ryan/pyprojectsort
  rev: v0.2.2
  hooks:
  - id: pyprojectsort