# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"#\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x0ePersonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\rPersonService\x12\x38\n\x0c\x43reatePerson\x12\x0f.example.Person\x1a\x17.example.PersonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=26
  _globals['_PERSON']._serialized_end=61
  _globals['_PERSONRESPONSE']._serialized_start=63
  _globals['_PERSONRESPONSE']._serialized_end=96
  _globals['_PERSONSERVICE']._serialized_start=98
  _globals['_PERSONSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
